<a href="https://colab.research.google.com/github/jmcnerney1/Jack-Mcnerney-Python/blob/main/Jack-hw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [ ]:
## Enter answer here.
age_years = int(input("Enter your age in years: "))

age_seconds = age_years * 364 * 24 * 60 * 60

if age_seconds > 1000000000:
    print("You are more than a billion seconds old.")
else:
    print("You are less than a billion seconds old.")


Enter your age in years: 21
You are less than a billion seconds old.


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [ ]:
## Enter answer here.

name = ['Bill', 'Bob', 'Billy', 'Bob', 'Bobby', 'Phil', 'Philly', 'Frank', 'Franky', 'Todd']

for i in range(len(name)):
    print("Good morning,", name[i])

Good morning, Bill
Good morning, Bob
Good morning, Billy
Good morning, Bob
Good morning, Bobby
Good morning, Phil
Good morning, Philly
Good morning, Frank
Good morning, Franky
Good morning, Todd


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [ ]:
## Enter answer here.

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

for number in numbers:
  if number % 2 == 0:
    print(number)


2
4
6
8
10
12
14


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [ ]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2


[0, 1.5625, 251.53959999999998, 625]


### Q5. Write a program to print a year if it is a leap year.

In [ ]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

1900
1900 is a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [ ]:
names = ['Bill', 'Bob', 'Billy', 'Bob', 'Bobby', 'Phil', 'Philly', 'Frank', 'Franky', 'Todd']
upper_case_names = [name.upper() for name in names]
upper_case_names


['BILL',
 'BOB',
 'BILLY',
 'BOB',
 'BOBBY',
 'PHIL',
 'PHILLY',
 'FRANK',
 'FRANKY',
 'TODD']

### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [ ]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np

original = np.random.uniform(low=-100, high=100, size=100)

print("Largest number:", np.max(original))
print("Smallest number:", np.min(original))
print("Max:", np.max(original))
print("Min:", np.min(original))
print("Median:", np.median(original))
print("Standard Deviation:", np.std(original))

orig_sqrt = np.sqrt(original)



Largest number: 99.66111861722581
Smallest number: -99.55498018562734
Max: 99.66111861722581
Min: -99.55498018562734
Median: -15.31815315003277
Standard Deviation: 56.165447806867306


<ipython-input-16-16bb4bd6d9cc>:13: RuntimeWarning: invalid value encountered in sqrt
  orig_sqrt = np.sqrt(original)


In [ ]:
import numpy as np

original = np.random.uniform(low=-100, high=100, size=100)
mat_array = original.reshape(20, 5)
print(mat_array)

column_means = np.mean(mat_array, axis=0)
print("Mean of every column:", column_means)

row_sums = np.sum(mat_array, axis=1)
print("Sum of every row:", row_sums)
row_sums_list = row_sums.tolist()
print("List of row sums:", row_sums_list)


transpose_array = mat_array.T
print("Dimensions of transpose_array:", transpose_array.shape)

transpose_col_means = np.mean(transpose_array, axis=0)
print("Mean of every column in transpose_array:", transpose_col_means)

transpose_row_sums = np.sum(transpose_array, axis=1)
print("Sum of every row in transpose_array:", transpose_row_sums)


[[-12.86899387 -64.32437032  71.17370409  95.16635787 -13.74121225]
 [-21.76542128 -75.23892904  54.55086356  91.33979328 -10.09060509]
 [-18.41978241  63.55786185  35.57058487 -42.9182457  -60.58248413]
 [ 30.09850873  21.90258678 -47.58126016 -49.25646522  11.63941756]
 [-96.92265706 -38.94193125  41.52986753 -74.82076008 -77.06421602]
 [-46.82099244   0.30056164  34.23235194  98.87132057 -72.57289033]
 [ 68.38875231  24.22765132   0.73654218 -33.43390406 -43.48396008]
 [-56.4925468  -61.97780798 -56.63709661 -14.66217795 -59.81325535]
 [-21.84324076 -95.07308311  84.51703333  13.90031584  70.51751939]
 [ 41.24116272  40.72546163 -78.11182534 -60.10347061   4.80490819]
 [-53.92458079   4.89693187 -16.5037717   16.32255299  46.11077255]
 [-61.56120138  65.90770851 -72.32433141 -97.01929998  46.16488064]
 [-81.28228953  16.19490139  -2.86801749 -30.88166539  70.46893623]
 [  6.2185123  -72.49662366  27.98941269  55.61474466 -88.57971977]
 [  9.0611061   24.13883705  40.13175468 -75.477

In [ ]:
new_array = mat_array[2:10, :]
print(new_array)

new_array_2 = mat_array[-5:, -2:]
print(new_array_2)
print("Dimension of new_array_2:", new_array_2.shape)

new_array_3 = transpose_array[:3, -10:]
new_array_3


[[-18.41978241  63.55786185  35.57058487 -42.9182457  -60.58248413]
 [ 30.09850873  21.90258678 -47.58126016 -49.25646522  11.63941756]
 [-96.92265706 -38.94193125  41.52986753 -74.82076008 -77.06421602]
 [-46.82099244   0.30056164  34.23235194  98.87132057 -72.57289033]
 [ 68.38875231  24.22765132   0.73654218 -33.43390406 -43.48396008]
 [-56.4925468  -61.97780798 -56.63709661 -14.66217795 -59.81325535]
 [-21.84324076 -95.07308311  84.51703333  13.90031584  70.51751939]
 [ 41.24116272  40.72546163 -78.11182534 -60.10347061   4.80490819]]
[[ 46.40033875 -27.03304535]
 [ 28.41694432  82.76499028]
 [-93.01191147 -37.95589399]
 [-20.10670339  52.97050809]
 [-34.54529792 -32.84421299]]
Dimension of new_array_2: (5, 2)


array([[-53.92458079, -61.56120138, -81.28228953,   6.2185123 ,
          9.0611061 ,  75.60450586,  47.23586755,  60.64574964,
        -22.11710227, -70.7301095 ],
       [  4.89693187,  65.90770851,  16.19490139, -72.49662366,
         24.13883705,  71.70949464,  93.97120604,  23.70920406,
        -78.12686881,  19.12678517],
       [-16.5037717 , -72.32433141,  -2.86801749,  27.98941269,
         40.13175468,  -7.45917905, -40.00315581, -27.15725686,
        -67.0184845 , -31.97776771]])

### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [ ]:
# Write your answer here.
import numpy as np

diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]

menu = []
for i in range(len(diet)):
    if diet[i] in ('vegetarian', 'vegan'):
        if age[i] >= 21:
            menu.append('veg. fried rice with whiskey')
        else:
            menu.append('veg. fried rice with mocktail')
    elif diet[i] == 'pescetarian':
        if age[i] >= 21:
            menu.append('fish and white wine')
        else:
            menu.append('fish with mocktail')
    elif diet[i] in ('keto', 'omnivore'):
        if age[i] >= 21:
            menu.append('steak and red wine')
        else:
            menu.append('steak and red wine') # Assuming underage keto/omnivores also get steak

menu



['veg. fried rice with whiskey',
 'fish with mocktail',
 'veg. fried rice with mocktail',
 'steak and red wine',
 'fish and white wine',
 'steak and red wine',
 'steak and red wine',
 'veg. fried rice with whiskey',
 'steak and red wine',
 'steak and red wine',
 'veg. fried rice with mocktail',
 'steak and red wine',
 'steak and red wine',
 'veg. fried rice with whiskey',
 'veg. fried rice with whiskey']